let's just disable breakpad until
this https://code.google.com/p/google-breakpad/issues/detail?id=481 gets fixed

while breakpad provides some cool functionalities for bug reporting, c++11 just provides too many useful things, and until google decide to fix their shit we just disable it. The bug was reported in 2012 and google didn't give a fuck since then. This makes me feel like they aren't really going to fix it.

diff --git a/huggle/configure b/huggle/configure
--- a/huggle/configure
+++ b/huggle/configure
@@ -242,28 +242,28 @@ if [ ! -f huggle.pro ];then
     ok
 fi
 
-if [ $BREAKPAD -eq 0 ];then
-    if [ ! -d breakpad ];then
-        text "Breakpad library is not present, unpacking it..."
-        tar -zxf breakpad.tar.gz || exit 1;ok
-    fi 
-    text "Checking for breakpad library"
-    if [ ! -f libbreakpad_client.a ];then
-        ok
-        echo "Building it"
-        cd breakpad || exit 1
-        ./configure || exit 1
-        make || exit 1
-        if [ ! -f src/client/linux/libbreakpad_client.a ];then
-            echo "Failed to build breakpad, src/client/linux/libbreakpad_client.a not found"
-            exit 1
-        fi
-        cp src/client/linux/libbreakpad_client.a .. || exit 1
-        cd .. || exit 1
-    else
-        ok
-    fi
-fi
+#if [ $BREAKPAD -eq 0 ];then
+#    if [ ! -d breakpad ];then
+#        text "Breakpad library is not present, unpacking it..."
+#        tar -zxf breakpad.tar.gz || exit 1;ok
+#    fi 
+#    text "Checking for breakpad library"
+#    if [ ! -f libbreakpad_client.a ];then
+#        ok
+#        echo "Building it"
+#        cd breakpad || exit 1
+#        ./configure || exit 1
+#        make || exit 1
+#        if [ ! -f src/client/linux/libbreakpad_client.a ];then
+#            echo "Failed to build breakpad, src/client/linux/libbreakpad_client.a not found"
+#            exit 1
+#        fi
+#        cp src/client/linux/libbreakpad_client.a .. || exit 1
+#        cd .. || exit 1
+#    else
+#        ok
+#    fi
+#fi
 
 text "Executing update.sh... "
 
