extra

diff --git a/huggle/configure b/huggle/configure
--- a/huggle/configure
+++ b/huggle/configure
@@ -7,6 +7,11 @@ if [ "`which qmake`" = "" ];then
 	exit 1
 fi
 
+if [ ! -f update.sh ];then
+	echo "update.sh is missing!"
+	exit 1
+fi
+
 sh update.sh
 
 if [ ! -f version.txt ];then
