improved

diff --git a/huggle/configure b/huggle/configure
--- a/huggle/configure
+++ b/huggle/configure
@@ -1,25 +1,79 @@
 #!/bin/sh
 
+checkqt()
+{
+        echo -n "Checking if $1 or $2 is present... "
+        if [ "`apt-cache policy $1 | wc -l`" -gt 2 ];then
+            echo "OK"
+            return 0
+        fi
+
+        if [ "`apt-cache policy $2 | wc -l`" -gt 2 ];then
+            echo "OK"
+            return 0
+        fi
+
+        echo "FAILED"
+        echo "$1 neither $2 is present"
+        exit 1
+}
+
+
+checkpkg()
+{
+        echo -n "Checking if $1 is present... "
+	if [ "`apt-cache policy $1 | wc -l`" -gt 2 ];then
+            echo "OK"
+            return 0
+        fi
+        echo "FAILED"
+        echo "$1 is not present"
+        exit 1
+}
+
 echo "Checking all required packages..."
 
+echo -n "Checking for qmake... "
 if [ "`which qmake`" = "" ];then
 	echo "qt4-qmake is not installed!"
 	exit 1
 fi
 
+echo "OK"
+
+if [ "`which apt-cache`" = "" ];then
+	echo "WARNING: Unable to verify packages, let's just hope they are all installed"
+else
+	checkpkg "g++"
+        checkqt "libqt4-dbus" "libqt5-dbus"
+        checkqt "libqt4-dev" "libqt5-dev"
+        checkqt "libqt4-network" "libqt5-network"
+        checkqt "libqt4-opengl" "libqt5-opengl"
+fi
+
+echo -n "Executing update.sh... "
 if [ ! -f update.sh ];then
 	echo "update.sh is missing!"
 	exit 1
 fi
 
-sh update.sh
+sh update.sh || exit 1
 
+echo "OK"
+
+echo -n "Checking if version.txt exist... "
 if [ ! -f version.txt ];then
 	echo "Error! unable to create a version file!"
 	exit 1
 fi
 
+echo "OK"
+
+echo -n "Creating makefile... "
+
 qmake || exit 1
+
+echo "OK"
 
 echo "Everything is ready, you can build huggle by typing"
 echo "make"
